<?php
/**
 * $Id: xoops_version.php v 1.0 8 May 2004 hsalazar Exp $
 * Module: Wordbook - a multicategory glossary
 * Version: v 1.00
 * Release Date: 8 May 2004
 * Author: hsalazar
 * Licence: GNU
 */

// XOOPS2 - Xwords 0.46
// WEBMASTER @ KANPYO.NET, 2006.

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;
$mydirname = basename( dirname( __FILE__ ) ) ;
$MYDIRNAME = strtoupper($mydirname);

$modversion['name'] = $MYDIRNAME;
$modversion['version'] = 0.47;
$modversion['description'] = constant("_MI_{$MYDIRNAME}_MD_DESC");
$modversion['author'] = "Aiba<br />(http://www.kanpyo.net/)";
$modversion['credits'] = "Original: Catzwolf<br />XOOPS Project";
$modversion['help'] = "";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/xwords_slogo.png";
$modversion['dirname'] = $mydirname;

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "{$mydirname}_cat";
$modversion['tables'][1] = "{$mydirname}_ent";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "{$mydirname}_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'entry.php';
$modversion['comments']['itemName'] = 'entryID';

// Menu
$modversion['hasMain'] = 1;
global $xoopsUser, $xoopsModuleConfig;
$i = 1;
if ( is_object($xoopsUser) )
	{
	if ( $xoopsUser->isAdmin() )
		{
		$modversion['sub'][$i]['name'] = constant("_MI_{$MYDIRNAME}_SUB_SMNAME0");
		$modversion['sub'][$i]['url'] = "admin/index.php";
		$i++;
		$modversion['sub'][$i]['name'] = constant("_MI_{$MYDIRNAME}_SUB_SMNAME1");
		$modversion['sub'][$i]['url'] = "admin/entry.php";
		$i++;
		}
	elseif ( isset($xoopsModuleConfig['allowsubmit']) && $xoopsModuleConfig["allowsubmit"] )
		{
		$modversion['sub'][$i]['name'] = constant("_MI_{$MYDIRNAME}_SUB_SMNAME1");
		$modversion['sub'][$i]['url'] = "submit.php";
		$i++;
		}
	}

if ( isset($xoopsModuleConfig['allowreq']) && $xoopsModuleConfig["allowreq"])
	{
	$modversion['sub'][$i]['name'] = constant("_MI_{$MYDIRNAME}_SUB_SMNAME2");
	$modversion['sub'][$i]['url'] = "request.php";
	$i++;
	}

$modversion['sub'][$i]['name'] = constant("_MI_{$MYDIRNAME}_SUB_SMNAME3");
$modversion['sub'][$i]['url'] = "search.php";
$i++;

if ( isset($xoopsModuleConfig['catsinmenu']) && $xoopsModuleConfig['catsinmenu'] && $xoopsModuleConfig['multicats'])
	{
	$xoopsDB =& Database::getInstance();
	$myts = & MyTextSanitizer ::getInstance();
	$cat_table = $xoopsDB->prefix( "{$mydirname}_cat" );
	$sql = $xoopsDB->query("SELECT categoryID, name FROM $cat_table ORDER BY weight ASC");
	while ( list( $categoryID, $name ) = $xoopsDB->fetchRow( $sql ) )
		{
		$name = $myts->makeTboxData4Show($name);
		$categoryID = intval($categoryID);
		$modversion['sub'][$i]['name'] = $name;
		$modversion['sub'][$i]['url'] = 'category.php?categoryID='.$categoryID;
		$i++;
		}
	}

// Blocks
$modversion['blocks'][1]['file'] = "entries_new.php";
$modversion['blocks'][1]['name'] = $MYDIRNAME.constant("_MI_{$MYDIRNAME}_ENTRIESNEW");
$modversion['blocks'][1]['description'] = "Shows new entries";
$modversion['blocks'][1]['show_func'] = "{$mydirname}_b_entries_new_show";
$modversion['blocks'][1]['edit_func'] = "{$mydirname}_b_entries_new_edit";
$modversion['blocks'][1]['options'] = "datesub|5";
$modversion['blocks'][1]['template'] = ($mydirname == "xwords") ? "entries_new.html" : "{$mydirname}_new.html";

$modversion['blocks'][2]['file'] = "entries_top.php";
$modversion['blocks'][2]['name'] = $MYDIRNAME.constant("_MI_{$MYDIRNAME}_ENTRIESTOP");
$modversion['blocks'][2]['description'] = "Shows popular entries";
$modversion['blocks'][2]['show_func'] = "{$mydirname}_b_entries_top_show";
$modversion['blocks'][2]['edit_func'] = "{$mydirname}_b_entries_top_edit";
$modversion['blocks'][2]['options'] = "counter|5";
$modversion['blocks'][2]['template'] = ($mydirname == "xwords") ? "entries_top.html" : "{$mydirname}_top.html";

$modversion['blocks'][3]['file'] = "random_term.php";
$modversion['blocks'][3]['name'] = $MYDIRNAME.constant("_MI_{$MYDIRNAME}_RANDOMTERM");
$modversion['blocks'][3]['description'] = "Shows a random term";
$modversion['blocks'][3]['show_func'] = "{$mydirname}_b_entries_random_show";
$modversion['blocks'][3]['template'] = ($mydirname == "xwords") ? "entries_random.html" : "{$mydirname}_random.html";

$modversion['blocks'][4]['file'] = "term_initial.php";
$modversion['blocks'][4]['name'] = $MYDIRNAME.constant("_MI_{$MYDIRNAME}_TERMINITIAL");
$modversion['blocks'][4]['description'] = "Shows a letter";
$modversion['blocks'][4]['show_func'] = "{$mydirname}_b_entries_initial_show";
$modversion['blocks'][4]['template'] = ($mydirname == "xwords") ? "entries_initial.html" : "{$mydirname}_initial.html";

$modversion['blocks'][5]['file'] = "term_d3com.php";
$modversion['blocks'][5]['name'] = $MYDIRNAME.constant("_MI_{$MYDIRNAME}_COMBLOCK");
$modversion['blocks'][5]['description'] = "Shows a d3comments";
$modversion['blocks'][5]['show_func'] = "{$mydirname}_b_d3comment_show";
$modversion['blocks'][5]['template'] = ($mydirname == "xwords") ? "d3comment.html" : "{$mydirname}_d3comment.html";

// Templates
$modversion['templates'][1]['file'] = "{$mydirname}_category.html";
$modversion['templates'][1]['description'] = 'Display categories';
$modversion['templates'][2]['file'] = "{$mydirname}_index.html";
$modversion['templates'][2]['description'] = 'Display index';
$modversion['templates'][3]['file'] = "{$mydirname}_preview.html";
$modversion['templates'][3]['description'] = 'preview a definition';
$modversion['templates'][4]['file'] = "{$mydirname}_entry.html";
$modversion['templates'][4]['description'] = 'Display entry';
$modversion['templates'][5]['file'] = "{$mydirname}_letter.html";
$modversion['templates'][5]['description'] = 'Display letter';
$modversion['templates'][6]['file'] = "{$mydirname}_search.html";
$modversion['templates'][6]['description'] = 'Search in glossary';
$modversion['templates'][7]['file'] = "{$mydirname}_request.html";
$modversion['templates'][7]['description'] = 'Request a definition';
$modversion['templates'][8]['file'] = "{$mydirname}_submit.html";
$modversion['templates'][8]['description'] = 'Entry a term';

// Config Settings (only for modules that need config settings generated automatically)
$cf=1;
$modversion['config'][$cf]['name'] = 'perpage';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_PERPAGE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_PERPAGEDSC";
$modversion['config'][$cf]['formtype'] = 'select';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 20;
$modversion['config'][$cf]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$cf++;
$modversion['config'][$cf]['name'] = 'indexperpage';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_PERPAGEINDEX";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_PERPAGEINDEXDSC";
$modversion['config'][$cf]['formtype'] = 'select';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 20;
$modversion['config'][$cf]['options'] = array( '5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$cf++;
$modversion['config'][$cf]['name'] = 'allowreq';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_ALLOWREQ";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_ALLOWREQDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'reqreply';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_REQREPLY";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_REQREPLYDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'allowsubmit';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_ALLOWSUBMIT";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_ALLOWSUBMITDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'autoapprove';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_AUTOAPPROVE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_AUTOAPPROVEDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'dhtmluse';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_DHTMLUSE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_DHTMLUSEDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'multicats';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_MULTICATS";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_MULTICATSDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 1;

$cf++;
$modversion['config'][$cf]['name'] = 'catsinmenu';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_CATSINMENU";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_CATSINMENUDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 1;

$cf++;
$modversion['config'][$cf]['name'] = 'adminhits';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_ALLOWADMINHITS";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_ALLOWADMINHITSDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 1;

$cf++;
$modversion['config'][$cf]['name'] = 'mailtoadmin';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_MAILTOADMIN";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_MAILTOADMINDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'rndlength';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_RANDOMLENGTH";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_RANDOMLENGTHDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 100;

$cf++;
$modversion['config'][$cf]['name'] = 'linkterms';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_LINKTERMS";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_LINKTERMSDSC";
$modversion['config'][$cf]['formtype'] = 'select';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;
$modversion['config'][$cf]['options'] = array(
	"_MI_{$MYDIRNAME}_LINKTERMSOP0DSC" => 0,
	"_MI_{$MYDIRNAME}_LINKTERMSOP1DSC" => 1,
	"_MI_{$MYDIRNAME}_LINKTERMSOP2DSC" => 2,
	"_MI_{$MYDIRNAME}_LINKTERMSOP3DSC" => 3,
);

$cf++;
$modversion['config'][$cf]['name'] = 'spattern';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_SPATTERN";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_SPATTERNDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = constant("_MI_{$MYDIRNAME}_SPATTERNDEFAULT");

$cf++;
$modversion['config'][$cf]['name'] = 'linktermsposition';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_LINKTERMSPOSI";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_LINKTERMSPOSIDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'linktermstitle';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_LINKTERMSTITLE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_LINKTERMSTITLEDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = constant("_MI_{$MYDIRNAME}_LINKTERMSDEFAULTTITLE");

$cf++;
$modversion['config'][$cf]['name'] = 'allowedtypes';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_FILETYPES";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_FILETYPESDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = '';

$cf++;
$modversion['config'][$cf]['name'] = 'uploadmax';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_UPLOADMAX";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_UPLOADMAXDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = '300';

$cf++;
$modversion['config'][$cf]['name'] = 'amazon_id';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_AMAZON";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_AMAZONDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = '';

$cf++;
$modversion['config'][$cf]['name'] = 'readme1st';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_README";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_READMEDSC";
$modversion['config'][$cf]['formtype'] = 'textarea';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = constant("_MI_{$MYDIRNAME}_READMEDEF");

$cf++;
$modversion['config'][$cf]['name'] = 'titleblockuse';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_TITLEBLOCKUSE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_TITLEBLOCKUSEDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 1;

$cf++;
$modversion['config'][$cf]['name'] = 'h1id';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_H1ID";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_H1IDDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = 'xwords_titlelogo.gif';

$cf++;
$modversion['config'][$cf]['name'] = 'strfformat';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_STRFFORMAT";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_STRFFORMATDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = '';

$cf++;
$modversion['config'][$cf]['name'] = 'letterformat';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_LETTERFORMAT";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_LETTERFORMATDSC";
$modversion['config'][$cf]['formtype'] = 'select';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = 'letter_format01.php';
$modversion['config'][$cf]['options'] = array(
	"_MI_{$MYDIRNAME}_LETTERFORMAT01" => 'letter_format01.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT02" => 'letter_format02.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT03" => 'letter_format03.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT04" => 'letter_format04.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT05" => 'letter_format05.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT06" => 'letter_format06.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT07" => 'letter_format07.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT08" => 'letter_format08.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT09" => 'letter_format09.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT10" => 'letter_format10.php',
	"_MI_{$MYDIRNAME}_LETTERFORMAT11" => 'letter_format11.php',
);

$cf++;
$modversion['config'][$cf]['name'] = 'submitterlink';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_SUBMITTERLINK";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_SUBMITTERLINKDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 1;

$cf++;
$modversion['config'][$cf]['name'] = 'catsarrayuse';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_CATSARRAYUSE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_CATSARRAYUSEDSC";
$modversion['config'][$cf]['formtype'] = 'yesno';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'blocksperpage';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_BLOCKSPERPAGE";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_BLOCKSPERPAGEDSC";
$modversion['config'][$cf]['formtype'] = 'select';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 5;
$modversion['config'][$cf]['options'] = array( '0' => 0,'5' => 5, '10' => 10, '15' => 15, '20' => 20, '25' => 25, '30' => 30, '50' => 50 );

$cf++;
$modversion['config'][$cf]['name'] = 'comment_dirname';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_COM_DIRNAME";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_COM_DIRNAMEDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'text';
$modversion['config'][$cf]['default'] = '';

$cf++;
$modversion['config'][$cf]['name'] = 'comment_forum_id';
$modversion['config'][$cf]['title'] = "_MI_{$MYDIRNAME}_COM_FORUM_ID";
$modversion['config'][$cf]['description'] = "_MI_{$MYDIRNAME}_COM_FORUM_IDDSC";
$modversion['config'][$cf]['formtype'] = 'textbox';
$modversion['config'][$cf]['valuetype'] = 'int';
$modversion['config'][$cf]['default'] = 0;

$cf++;
$modversion['config'][$cf]['name'] = 'comment_order';
$modversion['config'][$cf]['title'] =  "_MI_{$MYDIRNAME}_COM_ORDER";
$modversion['config'][$cf]['description'] =  "_MI_{$MYDIRNAME}_COM_ORDERDSC";
$modversion['config'][$cf]['formtype'] =  'select';
$modversion['config'][$cf]['valuetype'] =  'text';
$modversion['config'][$cf]['default'] =  'desc';
$modversion['config'][$cf]['options'] =  array( '_OLDESTFIRST' => 'asc' , '_NEWESTFIRST' => 'desc' );

$cf++;
$modversion['config'][$cf]['name'] =  'comment_view';
$modversion['config'][$cf]['title'] =  "_MI_{$MYDIRNAME}_COM_VIEW";
$modversion['config'][$cf]['description'] =  "_MI_{$MYDIRNAME}_COM_VIEWDSC";
$modversion['config'][$cf]['formtype'] =  'select';
$modversion['config'][$cf]['valuetype'] =  'text';
$modversion['config'][$cf]['default'] =  'listposts_flat';
$modversion['config'][$cf]['options'] =  array( '_FLAT' => 'listposts_flat' , '_THREADED' => 'listtopics' );

$cf++;
$modversion['config'][$cf]['name'] =  'comment_posts_num';
$modversion['config'][$cf]['title'] =  "_MI_{$MYDIRNAME}_COM_POSTSNUM";
$modversion['config'][$cf]['description'] =  '';
$modversion['config'][$cf]['formtype'] =  'textbox';
$modversion['config'][$cf]['valuetype'] =  'int';
$modversion['config'][$cf]['default'] =  '10';
$modversion['config'][$cf]['options'] =  array();


// On Install
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'install_ok' && $_POST['module'] != 'xwords' && $_POST['module'] == $mydirname && file_exists( XOOPS_ROOT_PATH . "/modules/{$mydirname}/include/oninstall.inc.php" ) )
	{
	include XOOPS_ROOT_PATH . "/modules/{$mydirname}/include/oninstall.inc.php" ;
	}

// On Update
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] && file_exists( XOOPS_ROOT_PATH . "/modules/{$mydirname}/include/onupdate.inc.php" ) )
	{
	include XOOPS_ROOT_PATH . "/modules/{$mydirname}/include/onupdate.inc.php" ;
	}

?>
