<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'næste 0','næste','næste 2','næste 3','næste 4','næste 5',
	'næste 6','næste 7','næste 8','næste 9','næste 10','næste 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'næste AM 0','næste AM 1','næste AM 2','næste AM 3','næste AM 4','næste AM 5',
	'næste AM 6','næste AM 7','næste AM 8','næste AM 9','næste AM 10','næste AM 11'
	) ;

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1.','2.','3.','4.','5.','6.','7.','8.','9.',
	'10.','11.','12.','13.','14.','15.','16.','17.','18.','19.',
	'20.','21.','22.','23.','24.','25.','26.','27.','28.','29.',
	'30.','31.'
	) ;

// Can use tags
$this->date_long_names = array(
	'0.','1.','2.','3.','4.','5.','6.','7.','8.','9.',
	'10.','11.','12.','13.','14.','15.','16.','17.','18.','19.',
	'20.','21.','22.','23.','24.','25.','26.','27.','28.','29.',
	'30.','31.'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Uge0','Uge1','Uge2','Uge3','Uge4','Uge5','Uge6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Sø','Ma','Ti','On','To','Fr','Lø','Sø') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Søn','Man','Tirs','Ons','Tors','Fre','Lør','Søn') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Søndag','Mandag','Tirsdag','Onsdag','Torsdag','Fredag','Lørdag','Søndag') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Feb','Mar','Apr','Maj','Jun','Jul','Aug','Sep','Okt','Nov','Dec') ;

// Can use tags
$this->month_middle_names = array('0','Jan','Feb','Mar','Apr','Maj','Jun','Jul','Aug','Sep','Okt','Nov','Dec') ;

// Can use tags
$this->month_long_names = array('0','Januar','Februar','Marts','April','Maj','Juni','Juli','August','September','Oktober','November','December') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'Søn','MO'=>'Man','TU'=>'Tirs','WE'=>'Ons','TH'=>'Tors','FR'=>'Fre','SA'=>'Lør') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1. Sunday','1MO'=>'1. Mandag','1TU'=>'1. Tirsdag','1WE'=>'1. Onsdag','1.'=>'1. Torsdag','1FR'=>'1. Fredag','1SA'=>'1. Lørdag',
	'2SU'=>'2. Sunday','2MO'=>'2. Mandag','2TU'=>'2. Tirsdag','2WE'=>'2. Onsdag','2.'=>'2. Torsdag','2FR'=>'2. Fredag','2SA'=>'2. Lørdag',
	'3SU'=>'3. Sunday','3MO'=>'3. Mandag','3TU'=>'3. Tirsdag','3WE'=>'3. Onsdag','3.'=>'3. Torsdag','3FR'=>'3. Fredag','3SA'=>'3. Lørdag',
	'4SU'=>'4. Sunday','4MO'=>'4. Mandag','4TU'=>'4. Tirsdag','4WE'=>'4. Onsdag','4.'=>'4. Torsdag','4FR'=>'4. Fredag','4SA'=>'4. Lørdag',
	'-1SU'=>'Sidste Søndag','-1MO'=>'Sidste Mandag','-1TU'=>'Sidste Tirsdag','-1WE'=>'Sidste Onsdag','-1.'=>'Sidste Torsdag','-1FR'=>'Sidste Fredag','-1SA'=>'Sidste Lørdag'
	) ;



?>